# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}

name: 'Az-Acme'
description: 'The simplest ACME Issuer for Azure Key Vault'
inputs:
  verb:
    description:
      'The verb to execute on the CLI, for example "register" or "order".'
    required: true
  args:
    description:
      'Additional command line arguments to provide. These are the same as per CLI documentation.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.verb }}
  - ${{ inputs.args }}